name: Build and Test

on: [push]

jobs:
    build:
        name: Build client

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: |
                  npm config set “@fortawesome:registry” https://npm.fontawesome.com/
                  npm config set “//npm.fontawesome.com/:_authToken” ${FONT_AWESOME_NPM_TOKEN}
                  yarn
              env:
                  FONT_AWESOME_NPM_TOKEN: ${{ secrets.FONT_AWESOME_NPM_TOKEN }}
            - name: Run linter
              run: yarn lint
            - name: Build Typescript
              run: yarn build
            - name: Run tests
              run: yarn test
